# Generated by Django 5.1.1 on 2024-09-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Product',
        ),
    ]
